component_management:
  individual_components:
    - component_id: antithrow
      name: antithrow
      paths:
        - packages/antithrow
    - component_id: eslint-plugin
      name: "@antithrow/eslint-plugin"
      paths:
        - packages/eslint-plugin
